apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: bsc-backendconfig
spec:
  timeoutSec: 40
  connectionDraining:
    drainingTimeoutSec: 60
  sessionAffinity:
    affinityType: "CLIENT_IP"
    affinityCookieTtlSec: 50
